#!/usr/bin/env python3
"""Write src/skelly-charuco/dict4x4_250_rot0.ts from OpenCV DICT_4X4_250 (rotation-0 first 2 bytes per id)."""

from __future__ import annotations

import json
import pathlib
import platform
import sys

import cv2


def main() -> None:
    b = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_250).bytesList
    flat: list[int] = [int(x) for row in b for x in row.flatten().tolist()[:2]]
    if len(flat) != 250 * 2:
        raise SystemExit(f"expected 500 bytes, got {len(flat)}")

    pyver = platform.python_version()
    cvver = cv2.__version__
    bytes_csv = ",".join(str(x) for x in flat)

    body = f"""/**
 * Auto-generated by scripts/export_dict4x4_250_ts.py from OpenCV DICT_4X4_250 — do not edit.
 *
 * Provenance: Python {pyver} · OpenCV {cvver}. Regenerate after upgrading OpenCV if detection diverges.
 */
export const DICT_4X4_250_SOURCE_PYTHON_VERSION = {json.dumps(pyver)};
export const DICT_4X4_250_SOURCE_OPENCV_VERSION = {json.dumps(cvver)};
export const DICT_4X4_250_ROT0_BYTES = new Uint8Array([{bytes_csv}]);
"""

    root = pathlib.Path(__file__).resolve().parents[1]
    out_dir = root / "src" / "skelly-charuco"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "dict4x4_250_rot0.ts"
    out_path.write_text(body, encoding="utf-8")
    print(f"Wrote {out_path}")
    print(f"python={pyver} opencv={cvver}", file=sys.stderr)


if __name__ == "__main__":
    main()
