/**
 * Emits one feasibility blob per {@link PAPER_OPTIONS} preset (see `src/print/charucoLayout.ts`).
 *
 * Node uses the no-canvas banner fallback — tables match that tiling path.
 *
 * Keep paper ids and mm dimensions aligned with `PAPER_OPTIONS` in charucoLayout.ts.
 */
import {mkdirSync, unlinkSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

import {computeTilingInfo, computeTilingInfoMatchingPageCount} from '../src/print/tiling.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

const PAPER_OPTIONS: {id: string; wMm: number; hMm: number}[] = [
    {id: 'a4', wMm: 210, hMm: 297},
    {id: 'a3', wMm: 297, hMm: 420},
    {id: 'letter', wMm: 215.9, hMm: 279.4},
    {id: 'tabloid', wMm: 279.4, hMm: 431.8},
];

const BOARD_GRID_MIN = 2;
const BOARD_GRID_MAX = 40;
const PAGE_COUNT_MIN = 1;
const PAGE_COUNT_MAX = 9;
const SQ_MIN = 10;
const SQ_MAX = 200;

const GRID_SPAN = BOARD_GRID_MAX - BOARD_GRID_MIN + 1;
const SLOT_COUNT_PER_PAPER = GRID_SPAN * GRID_SPAN;
const SQ_BITMAP_BYTES = Math.ceil((SQ_MAX - SQ_MIN + 1) / 8);

function gridSlotIndex(squaresX: number, squaresY: number): number {
    return (squaresX - BOARD_GRID_MIN) * GRID_SPAN + (squaresY - BOARD_GRID_MIN);
}

function encodeMmListToBitmap(mmList: number[], dst: Uint8Array, byteOffset: number): void {
    dst.fill(0, byteOffset, byteOffset + SQ_BITMAP_BYTES);
    for (const mm of mmList) {
        const bit = mm - SQ_MIN;
        dst[byteOffset + (bit >> 3)]! |= 1 << (bit & 7);
    }
}

function toBase64(u8: Uint8Array): string {
    return Buffer.from(u8.buffer, u8.byteOffset, u8.byteLength).toString('base64');
}

function squareSizeFitsTargetPageCountEitherOrientation(
    squaresX: number,
    squaresY: number,
    squareMm: number,
    paperWMm: number,
    paperHMm: number,
    targetPages: number,
): boolean {
    if (computeTilingInfoMatchingPageCount(squaresX, squaresY, squareMm, paperWMm, paperHMm, targetPages) !== null) {
        return true;
    }
    if (squaresX !== squaresY) {
        return (
            computeTilingInfoMatchingPageCount(squaresY, squaresX, squareMm, paperWMm, paperHMm, targetPages) !== null
        );
    }
    return false;
}

function maxSquareMmForGridAndPages(
    squaresX: number,
    squaresY: number,
    paperWMm: number,
    paperHMm: number,
    targetPages: number,
): number | null {
    for (let s = SQ_MAX; s >= SQ_MIN; s--) {
        if (squareSizeFitsTargetPageCountEitherOrientation(squaresX, squaresY, s, paperWMm, paperHMm, targetPages)) {
            return s;
        }
    }
    return null;
}

function validTargetPageCountsForGrid(
    squaresX: number,
    squaresY: number,
    paperWMm: number,
    paperHMm: number,
): number[] {
    const out: number[] = [];
    for (let p = PAGE_COUNT_MIN; p <= PAGE_COUNT_MAX; p++) {
        let any = false;
        for (let s = SQ_MIN; s <= SQ_MAX; s++) {
            if (squareSizeFitsTargetPageCountEitherOrientation(squaresX, squaresY, s, paperWMm, paperHMm, p)) {
                any = true;
                break;
            }
        }
        if (any) {
            out.push(p);
        }
    }
    return out;
}

function enumerateValidSquareSizes(
    squaresX: number,
    squaresY: number,
    paperWMm: number,
    paperHMm: number,
): number[] {
    const out = new Set<number>();
    for (let s = SQ_MIN; s <= SQ_MAX; s++) {
        if (computeTilingInfo(squaresX, squaresY, s, paperWMm, paperHMm) !== null) {
            out.add(s);
        } else if (squaresX !== squaresY && computeTilingInfo(squaresY, squaresX, s, paperWMm, paperHMm) !== null) {
            out.add(s);
        }
    }
    return [...out].sort((a, b) => a - b);
}

function emitConstants(outDir: string): void {
    const rowsJson = JSON.stringify(PAPER_OPTIONS.map((p) => ({id: p.id, wMm: p.wMm, hMm: p.hMm})));
    const body = `/**
 * AUTO-GENERATED by scripts/generate-tiling-feasibility.ts — do not edit.
 */
export const TILING_FEASIBILITY_GRID_MIN = ${BOARD_GRID_MIN} as const;
export const TILING_FEASIBILITY_GRID_MAX = ${BOARD_GRID_MAX} as const;
export const TILING_FEASIBILITY_GRID_SPAN = ${GRID_SPAN} as const;
export const TILING_FEASIBILITY_SLOTS_PER_PAPER = ${SLOT_COUNT_PER_PAPER} as const;
export const TILING_FEASIBILITY_SQ_MM_MIN = ${SQ_MIN} as const;
export const TILING_FEASIBILITY_SQ_MM_MAX = ${SQ_MAX} as const;
export const TILING_FEASIBILITY_SQ_BITMAP_BYTES = ${SQ_BITMAP_BYTES} as const;
export const TILING_FEASIBILITY_PAGE_COUNT_MIN = ${PAGE_COUNT_MIN} as const;
export const TILING_FEASIBILITY_PAGE_COUNT_MAX = ${PAGE_COUNT_MAX} as const;

const FEASIBILITY_PAPER_ROWS = ${rowsJson} as readonly {readonly id: string; readonly wMm: number; readonly hMm: number}[];

export function feasibilityPaperIdFromDims(paperWMm: number, paperHMm: number): string | undefined {
    for (const row of FEASIBILITY_PAPER_ROWS) {
        if (row.wMm === paperWMm && row.hMm === paperHMm) {
            return row.id;
        }
    }
    return undefined;
}

export function resolveFeasibilityGridSlot(squaresX: number, squaresY: number): number | undefined {
    if (
        squaresX < TILING_FEASIBILITY_GRID_MIN ||
        squaresX > TILING_FEASIBILITY_GRID_MAX ||
        squaresY < TILING_FEASIBILITY_GRID_MIN ||
        squaresY > TILING_FEASIBILITY_GRID_MAX
    ) {
        return undefined;
    }
    return (squaresX - TILING_FEASIBILITY_GRID_MIN) * TILING_FEASIBILITY_GRID_SPAN +
        (squaresY - TILING_FEASIBILITY_GRID_MIN);
}
`;
    writeFileSync(join(outDir, 'tilingFeasibilityConstants.ts'), body, 'utf8');
}

function emitPaperFile(outDir: string, paperId: string, b64ValidPages: string, b64MaxSq: string, b64AnySq: string): void {
    const body = `/**
 * AUTO-GENERATED by scripts/generate-tiling-feasibility.ts — do not edit.
 * Paper preset: ${paperId}
 */
import {decodeBytesFromBase64} from '../tilingFeasibilityCodec.js';

export const VALID_PAGES_BITS = new Uint16Array(decodeBytesFromBase64(${JSON.stringify(b64ValidPages)}).buffer);
export const MAX_SQ_MM_PACKED = new Int8Array(decodeBytesFromBase64(${JSON.stringify(b64MaxSq)}).buffer);
export const ANY_SQ_BITMAP = decodeBytesFromBase64(${JSON.stringify(b64AnySq)});
`;
    writeFileSync(join(outDir, `tilingFeasibilityPaper-${paperId}.ts`), body, 'utf8');
}

function main(): void {
    const outDir = join(__dirname, '..', 'src', 'print', 'generated');
    mkdirSync(outDir, {recursive: true});

    const legacyMonolith = join(outDir, 'tilingFeasibilityTables.ts');
    try {
        unlinkSync(legacyMonolith);
    } catch {
        /* absent */
    }

    emitConstants(outDir);

    for (const paper of PAPER_OPTIONS) {
        const {id, wMm, hMm} = paper;
        const validPagesBits = new Uint16Array(SLOT_COUNT_PER_PAPER);
        const maxSqMmPacked = new Int8Array(SLOT_COUNT_PER_PAPER * 9);
        const anySqBitmap = new Uint8Array(SLOT_COUNT_PER_PAPER * SQ_BITMAP_BYTES);

        for (let sx = BOARD_GRID_MIN; sx <= BOARD_GRID_MAX; sx++) {
            for (let sy = BOARD_GRID_MIN; sy <= BOARD_GRID_MAX; sy++) {
                const slot = gridSlotIndex(sx, sy);

                const targets = validTargetPageCountsForGrid(sx, sy, wMm, hMm);
                let bits = 0;
                for (const p of targets) {
                    bits |= 1 << (p - 1);
                }
                validPagesBits[slot] = bits;

                const squaresAny = enumerateValidSquareSizes(sx, sy, wMm, hMm);
                encodeMmListToBitmap(squaresAny, anySqBitmap, slot * SQ_BITMAP_BYTES);

                for (let p = PAGE_COUNT_MIN; p <= PAGE_COUNT_MAX; p++) {
                    const maxSq = maxSquareMmForGridAndPages(sx, sy, wMm, hMm, p);
                    maxSqMmPacked[slot * 9 + (p - 1)] = maxSq === null ? -1 : maxSq;
                }
            }
        }

        emitPaperFile(
            outDir,
            id,
            toBase64(new Uint8Array(validPagesBits.buffer)),
            toBase64(new Uint8Array(maxSqMmPacked.buffer)),
            toBase64(anySqBitmap),
        );
        console.warn(`Wrote tilingFeasibilityPaper-${id}.ts`);
    }

    console.warn(`Wrote tilingFeasibilityConstants.ts`);
}

main();
