/**
 * Emits one feasibility blob per paper preset (four parallel `tsx` subprocesses).
 *
 * Node has no canvas — banner strip uses {@link ORIGIN_PAGE_EXTRA_MM} (portrait layout) or
 * {@link ORIGIN_BANNER_STRIP_FALLBACK_NO_CANVAS_LANDSCAPE_MM} (landscape layout), not a single 77 mm slab for both.
 *
 * Keep paper ids and mm dimensions aligned with `PAPER_OPTIONS` in charucoLayout.ts.
 */
import {spawn} from 'node:child_process';
import {mkdirSync, unlinkSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

import {
    BOARD_GRID_MAX,
    BOARD_GRID_MIN,
    GRID_SPAN,
    PAGE_COUNT_MAX,
    PAGE_COUNT_MIN,
    SLOT_COUNT_PER_PAPER,
    SQ_BITMAP_BYTES,
    SQ_MAX,
    SQ_MIN,
} from './feasibilityCompute.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const tsxCli = join(repoRoot, 'node_modules/tsx/dist/cli.mjs');
const onePaperScript = join(__dirname, 'generate-tiling-feasibility-one-paper.ts');

const PAPER_OPTIONS: {id: string; wMm: number; hMm: number}[] = [
    {id: 'a4', wMm: 210, hMm: 297},
    {id: 'a3', wMm: 297, hMm: 420},
    {id: 'letter', wMm: 215.9, hMm: 279.4},
    {id: 'tabloid', wMm: 279.4, hMm: 431.8},
];

type PaperGenResult = {paperId: string; b64ValidPages: string; b64MaxSq: string; b64AnySq: string};

function emitConstants(outDir: string): void {
    const rowsJson = JSON.stringify(PAPER_OPTIONS.map((p) => ({id: p.id, wMm: p.wMm, hMm: p.hMm})));
    const body = `/**
 * AUTO-GENERATED by scripts/generate-tiling-feasibility.ts — do not edit.
 */
export const TILING_FEASIBILITY_GRID_MIN = ${BOARD_GRID_MIN} as const;
export const TILING_FEASIBILITY_GRID_MAX = ${BOARD_GRID_MAX} as const;
export const TILING_FEASIBILITY_GRID_SPAN = ${GRID_SPAN} as const;
export const TILING_FEASIBILITY_SLOTS_PER_PAPER = ${SLOT_COUNT_PER_PAPER} as const;
export const TILING_FEASIBILITY_SQ_MM_MIN = ${SQ_MIN} as const;
export const TILING_FEASIBILITY_SQ_MM_MAX = ${SQ_MAX} as const;
export const TILING_FEASIBILITY_SQ_BITMAP_BYTES = ${SQ_BITMAP_BYTES} as const;
export const TILING_FEASIBILITY_PAGE_COUNT_MIN = ${PAGE_COUNT_MIN} as const;
export const TILING_FEASIBILITY_PAGE_COUNT_MAX = ${PAGE_COUNT_MAX} as const;

const FEASIBILITY_PAPER_ROWS = ${rowsJson} as readonly {readonly id: string; readonly wMm: number; readonly hMm: number}[];

export function feasibilityPaperIdFromDims(paperWMm: number, paperHMm: number): string | undefined {
    for (const row of FEASIBILITY_PAPER_ROWS) {
        if (row.wMm === paperWMm && row.hMm === paperHMm) {
            return row.id;
        }
    }
    return undefined;
}

export function resolveFeasibilityGridSlot(squaresX: number, squaresY: number): number | undefined {
    if (
        squaresX < TILING_FEASIBILITY_GRID_MIN ||
        squaresX > TILING_FEASIBILITY_GRID_MAX ||
        squaresY < TILING_FEASIBILITY_GRID_MIN ||
        squaresY > TILING_FEASIBILITY_GRID_MAX
    ) {
        return undefined;
    }
    return (squaresX - TILING_FEASIBILITY_GRID_MIN) * TILING_FEASIBILITY_GRID_SPAN +
        (squaresY - TILING_FEASIBILITY_GRID_MIN);
}
`;
    writeFileSync(join(outDir, 'tilingFeasibilityConstants.ts'), body, 'utf8');
}

function emitPaperFile(outDir: string, paperId: string, b64ValidPages: string, b64MaxSq: string, b64AnySq: string): void {
    const body = `/**
 * AUTO-GENERATED by scripts/generate-tiling-feasibility.ts — do not edit.
 * Paper preset: ${paperId}
 */
import {decodeBytesFromBase64} from '../tilingFeasibilityCodec.js';

export const VALID_PAGES_BITS = new Uint16Array(decodeBytesFromBase64(${JSON.stringify(b64ValidPages)}).buffer);
export const MAX_SQ_MM_PACKED = new Int8Array(decodeBytesFromBase64(${JSON.stringify(b64MaxSq)}).buffer);
export const ANY_SQ_BITMAP = decodeBytesFromBase64(${JSON.stringify(b64AnySq)});
`;
    writeFileSync(join(outDir, `tilingFeasibilityPaper-${paperId}.ts`), body, 'utf8');
}

function runPaperSubprocess(paper: {id: string; wMm: number; hMm: number}): Promise<PaperGenResult> {
    return new Promise((resolve, reject) => {
        const proc = spawn(process.execPath, [tsxCli, onePaperScript, JSON.stringify(paper)], {
            cwd: repoRoot,
            stdio: ['ignore', 'pipe', 'pipe'],
        });
        let stdout = '';
        let stderr = '';
        proc.stdout?.on('data', (chunk: Buffer) => {
            stdout += chunk.toString('utf8');
        });
        proc.stderr?.on('data', (chunk: Buffer) => {
            stderr += chunk.toString('utf8');
        });
        proc.on('error', reject);
        proc.on('close', (code) => {
            if (code !== 0) {
                reject(new Error(`paper ${paper.id}: subprocess exited ${code}${stderr ? `\n${stderr}` : ''}`));
                return;
            }
            try {
                resolve(JSON.parse(stdout.trim()) as PaperGenResult);
            } catch (err) {
                reject(new Error(`paper ${paper.id}: invalid JSON stdout (${String(err)})`));
            }
        });
    });
}

async function main(): Promise<void> {
    const outDir = join(repoRoot, 'src', 'print', 'generated');
    mkdirSync(outDir, {recursive: true});

    const legacyMonolith = join(outDir, 'tilingFeasibilityTables.ts');
    try {
        unlinkSync(legacyMonolith);
    } catch {
        /* absent */
    }

    emitConstants(outDir);
    console.warn('Wrote tilingFeasibilityConstants.ts');

    const results = await Promise.all(PAPER_OPTIONS.map((paper) => runPaperSubprocess(paper)));
    for (const r of results) {
        emitPaperFile(outDir, r.paperId, r.b64ValidPages, r.b64MaxSq, r.b64AnySq);
        console.warn(`Wrote tilingFeasibilityPaper-${r.paperId}.ts`);
    }
}

main().catch((err) => {
    console.error(err);
    process.exitCode = 1;
});
